#!/bin/sh

script_path="$( dirname "$( readlink -f "$0" )")"

if uname | grep -q Linux; then
  LD_LIBRARY_PATH="${script_path}/bin:${LD_LIBRARY_PATH}" "${script_path}/bin/nw" "$script_path"
else
  open -a $script_path/bin/node-webkit.app
fi
